# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/diffusion_curvature',
                'doc_host': 'https://professorwug.github.io',
                'git_url': 'https://github.com/professorwug/diffusion_curvature',
                'lib_path': 'diffusion_curvature'},
  'syms': { 'diffusion_curvature.datasets': { 'diffusion_curvature.datasets.ellipsoid': ( 'datasets.html#ellipsoid',
                                                                                          'diffusion_curvature/datasets.py'),
                                              'diffusion_curvature.datasets.hyperboloid': ( 'datasets.html#hyperboloid',
                                                                                            'diffusion_curvature/datasets.py'),
                                              'diffusion_curvature.datasets.paraboloid': ( 'datasets.html#paraboloid',
                                                                                           'diffusion_curvature/datasets.py'),
                                              'diffusion_curvature.datasets.plane': ( 'datasets.html#plane',
                                                                                      'diffusion_curvature/datasets.py'),
                                              'diffusion_curvature.datasets.rejection_sample_for_ellipsoid': ( 'datasets.html#rejection_sample_for_ellipsoid',
                                                                                                               'diffusion_curvature/datasets.py'),
                                              'diffusion_curvature.datasets.rejection_sample_for_hyperboloid': ( 'datasets.html#rejection_sample_for_hyperboloid',
                                                                                                                 'diffusion_curvature/datasets.py'),
                                              'diffusion_curvature.datasets.rejection_sample_for_saddle': ( 'datasets.html#rejection_sample_for_saddle',
                                                                                                            'diffusion_curvature/datasets.py'),
                                              'diffusion_curvature.datasets.rejection_sample_for_torus': ( 'datasets.html#rejection_sample_for_torus',
                                                                                                           'diffusion_curvature/datasets.py'),
                                              'diffusion_curvature.datasets.sphere': ( 'datasets.html#sphere',
                                                                                       'diffusion_curvature/datasets.py'),
                                              'diffusion_curvature.datasets.torus': ( 'datasets.html#torus',
                                                                                      'diffusion_curvature/datasets.py')},
            'diffusion_curvature.distances': { 'diffusion_curvature.distances.phate_distances': ( 'manifold distances.html#phate_distances',
                                                                                                  'diffusion_curvature/distances.py')},
            'diffusion_curvature.entropy': { 'diffusion_curvature.entropy.diffusion_curvature_contra_noise': ( 'diffusion entropy '
                                                                                                               'curvature.sync-conflict-20230727-071559-nxphttx.html#diffusion_curvature_contra_noise',
                                                                                                               'diffusion_curvature/entropy.py'),
                                             'diffusion_curvature.entropy.diffusion_entropy_curvature_of_data': ( 'diffusion entropy '
                                                                                                                  'curvature.sync-conflict-20230727-071559-nxphttx.html#diffusion_entropy_curvature_of_data',
                                                                                                                  'diffusion_curvature/entropy.py'),
                                             'diffusion_curvature.entropy.diffusion_entropy_of_noise': ( 'diffusion entropy '
                                                                                                         'curvature.sync-conflict-20230727-071559-nxphttx.html#diffusion_entropy_of_noise',
                                                                                                         'diffusion_curvature/entropy.py'),
                                             'diffusion_curvature.entropy.local_diffusion_entropy_of_matrix': ( 'diffusion entropy '
                                                                                                                'curvature.sync-conflict-20230727-071559-nxphttx.html#local_diffusion_entropy_of_matrix',
                                                                                                                'diffusion_curvature/entropy.py')},
            'diffusion_curvature.graphtools': { 'diffusion_curvature.graphtools.DiffusionCurvature': ( 'core '
                                                                                                       '(graphtools).html#diffusioncurvature',
                                                                                                       'diffusion_curvature/graphtools.py'),
                                                'diffusion_curvature.graphtools.DiffusionCurvature.__init__': ( 'core '
                                                                                                                '(graphtools).html#diffusioncurvature.__init__',
                                                                                                                'diffusion_curvature/graphtools.py'),
                                                'diffusion_curvature.graphtools.DiffusionCurvature.curvature': ( 'core '
                                                                                                                 '(graphtools).html#diffusioncurvature.curvature',
                                                                                                                 'diffusion_curvature/graphtools.py'),
                                                'diffusion_curvature.graphtools.DiffusionCurvature.distances': ( 'core '
                                                                                                                 '(graphtools).html#diffusioncurvature.distances',
                                                                                                                 'diffusion_curvature/graphtools.py'),
                                                'diffusion_curvature.graphtools.DiffusionCurvature.entropy_of_diffusion': ( 'core '
                                                                                                                            '(graphtools).html#diffusioncurvature.entropy_of_diffusion',
                                                                                                                            'diffusion_curvature/graphtools.py'),
                                                'diffusion_curvature.graphtools.DiffusionCurvature.flattened_facsimile_of_graph': ( 'core '
                                                                                                                                    '(graphtools).html#diffusioncurvature.flattened_facsimile_of_graph',
                                                                                                                                    'diffusion_curvature/graphtools.py'),
                                                'diffusion_curvature.graphtools.DiffusionCurvature.power_diffusion_matrix': ( 'core '
                                                                                                                              '(graphtools).html#diffusioncurvature.power_diffusion_matrix',
                                                                                                                              'diffusion_curvature/graphtools.py'),
                                                'diffusion_curvature.graphtools.DiffusionCurvature.wasserstein_spread_of_diffusion': ( 'core '
                                                                                                                                       '(graphtools).html#diffusioncurvature.wasserstein_spread_of_diffusion',
                                                                                                                                       'diffusion_curvature/graphtools.py')},
            'diffusion_curvature.kernels': { 'diffusion_curvature.kernels.compute_anisotropic_affinities_from_graph': ( 'kernels.html#compute_anisotropic_affinities_from_graph',
                                                                                                                        'diffusion_curvature/kernels.py'),
                                             'diffusion_curvature.kernels.compute_anisotropic_diffusion_matrix_from_graph': ( 'kernels.html#compute_anisotropic_diffusion_matrix_from_graph',
                                                                                                                              'diffusion_curvature/kernels.py'),
                                             'diffusion_curvature.kernels.diffusion_matrix': ( 'kernels.html#diffusion_matrix',
                                                                                               'diffusion_curvature/kernels.py'),
                                             'diffusion_curvature.kernels.gaussian_kernel': ( 'kernels.html#gaussian_kernel',
                                                                                              'diffusion_curvature/kernels.py'),
                                             'diffusion_curvature.kernels.median_heuristic': ( 'kernels.html#median_heuristic',
                                                                                               'diffusion_curvature/kernels.py'),
                                             'diffusion_curvature.kernels.plot_3d': ( 'kernels.html#plot_3d',
                                                                                      'diffusion_curvature/kernels.py')},
            'diffusion_curvature.wasserstein': { 'diffusion_curvature.wasserstein.WassersteinDiffusionCurvature': ( 'wasserstein diffusion '
                                                                                                                    'curvature.html#wassersteindiffusioncurvature',
                                                                                                                    'diffusion_curvature/wasserstein.py'),
                                                 'diffusion_curvature.wasserstein.WassersteinDiffusionCurvature.__init__': ( 'wasserstein '
                                                                                                                             'diffusion '
                                                                                                                             'curvature.html#wassersteindiffusioncurvature.__init__',
                                                                                                                             'diffusion_curvature/wasserstein.py'),
                                                 'diffusion_curvature.wasserstein.WassersteinDiffusionCurvature.curvature_of_graph': ( 'wasserstein '
                                                                                                                                       'diffusion '
                                                                                                                                       'curvature.html#wassersteindiffusioncurvature.curvature_of_graph',
                                                                                                                                       'diffusion_curvature/wasserstein.py'),
                                                 'diffusion_curvature.wasserstein.WassersteinDiffusionCurvature.curvature_of_points': ( 'wasserstein '
                                                                                                                                        'diffusion '
                                                                                                                                        'curvature.html#wassersteindiffusioncurvature.curvature_of_points',
                                                                                                                                        'diffusion_curvature/wasserstein.py'),
                                                 'diffusion_curvature.wasserstein.WassersteinDiffusionCurvature.plot': ( 'wasserstein '
                                                                                                                         'diffusion '
                                                                                                                         'curvature.html#wassersteindiffusioncurvature.plot',
                                                                                                                         'diffusion_curvature/wasserstein.py'),
                                                 'diffusion_curvature.wasserstein.get_manifold_distances': ( 'wasserstein diffusion '
                                                                                                             'curvature.html#get_manifold_distances',
                                                                                                             'diffusion_curvature/wasserstein.py'),
                                                 'diffusion_curvature.wasserstein.wasserstein_spread_of_diffusion_matrix': ( 'wasserstein '
                                                                                                                             'diffusion '
                                                                                                                             'curvature.html#wasserstein_spread_of_diffusion_matrix',
                                                                                                                             'diffusion_curvature/wasserstein.py')}}}
