# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DiffusionMatrix": "00_core.ipynb",
         "plot_3d": "00_core.ipynb",
         "rejection_sample_for_torus": "11_dataset tests avg transition probs.ipynb",
         "torus": "11_dataset tests avg transition probs.ipynb",
         "rejection_sample_for_hyperboloid": "11_dataset tests avg transition probs.ipynb",
         "hyperboloid": "11_dataset tests avg transition probs.ipynb",
         "rejection_sample_for_ellipsoid": "11_dataset tests avg transition probs.ipynb",
         "ellipsoid": "11_dataset tests avg transition probs.ipynb",
         "rejection_sample_for_saddle": "11_dataset tests avg transition probs.ipynb",
         "paraboloid": "11_dataset tests avg transition probs.ipynb",
         "curvature": "12_differentiable_diffusion_curvature.ipynb",
         "laziness_decay": "03_laziness_decay.ipynb",
         "local_laziness": "04_region_limited_laziness.ipynb",
         "matpower": "sparse_matrices_exploration.ipynb"}

modules = ["core.py",
           "datasets.py",
           "laziness.py",
           "differentiable_laziness.py"]

doc_url = "https://x.riddle.press/diffusion_curvature/"

git_url = "https://github.com/professorwug/diffusion_curvature/tree/master/"

def custom_doc_links(name): return None
