# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DiffusionMatrix": "00_core.ipynb",
         "plot_3d": "00_core.ipynb",
         "rejection_sample": "01_datasets.ipynb",
         "torus": "01_datasets.ipynb",
         "curvature": "02_laziness.ipynb"}

modules = ["core.py",
           "datasets.py",
           "laziness.py"]

doc_url = "https://x.riddle.press/diffusion_curvature/"

git_url = "https://github.com/professorwug/diffusion_curvature/tree/master/"

def custom_doc_links(name): return None
