# AUTOGENERATED! DO NOT EDIT! File to edit: ../09a_curvature_curves_in_euclidean_space.ipynb.

# %% auto 0
__all__ = ['rate_of_change_of_entropy']

# %% ../09a_curvature_curves_in_euclidean_space.ipynb 30
from .comparisons import diffusion_entropy_curvature_of_data
def rate_of_change_of_entropy(X, k = 10, max=32):
    ts = list(range(1,max))
    entropies = np.empty((len(X),len(ts)))
    for idx, t in tqdm(enumerate(ts)):
        entropies[:,idx] = diffusion_entropy_curvature_of_data(X,t, k=k)
    return entropies
