# AUTOGENERATED! DO NOT EDIT! File to edit: ../06c_volume_comparison_curvature.ipynb.

# %% auto 0
__all__ = ['coordinate_grid']

# %% ../06c_volume_comparison_curvature.ipynb 3
import numpy as np
def coordinate_grid(dim, n_points_per_dim):
    # TODO: Generalize to dimensions above 3
    xs = [np.linspace(-1,1,n_points_per_dim) for i in range(dim)]
    match dim:
        case  2:
            M1, M2 = np.meshgrid(xs[0],xs[1])
            X = np.concatenate([M1[:,:,None], M2[:,:,None]], axis=-1).reshape(-1,dim)
            X = np.vstack([np.zeros(dim),X])
        case 3:
            M1, M2, M3 = np.meshgrid(xs[0],xs[1],xs[2])
            X = np.concatenate([M1[:,:,:,None], M2[:,:,:,None], M3[:,:,:,None]],axis=-1).reshape(-1,dim)
            X = np.vstack([np.zeros(dim),X])
        case _:
            raise NotImplementedError
    return X
